
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    env_file:
      - .env

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - 8080:80
    depends_on:
      - php
    env_file:
      - .env

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8080
        anonymous
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthz" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    volumes:
      - mercure_data:/data
      - mercure_config:/config


volumes:
  mercure_data:
  mercure_config: